export const GET_CURRENT_LOC_DATA = 'GET_CURRENT_LOC_DATA';
export const GET_END_POINT_LOC_DATA = 'GET_END_POINT_LOC_DATA';

export const GET_DATA_LOADING = 'GET_DATA_LOADING';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';