export const GET_CURRENT_LOC_DATA = 'GET_CURRENT_LOC_DATA';
export const GET_MEET_POINT_LOC_DATA = 'GET_MEET_POINT_LOC_DATA';

export const GET_EMAIL = 'GET_EMAIL';
export const GET_LOGIN = 'GET_LOGIN';
export const GET_PASS = 'GET_PASS';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const GET_MEET_POINT_MARKER_DATA = 'GET_MEET_POINT_MARKER_DATA';

export const GET_FRIEND_NAME = 'GET_FRIEND_NAME';
export const GET_REQUEST_ON_FRIENDSHIP = 'GET_REQUEST_ON_FRIENDSHIP'

export const GET_DATA_LOADING = 'GET_DATA_LOADING';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';

